// Copyright © 2025, United States Government, as represented by the Administrator of the National Aeronautics and Space Administration. All rights reserved.
// 
// The “FRET : Formal Requirements Elicitation Tool - Version 3.0” software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0. 
// 
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
// This Antlr4 file was machine-generated by the BNF converter
lexer grammar CopilotLexer;
// Predefined regular expressions in BNFC
fragment LETTER  : CAPITAL | SMALL ;
fragment CAPITAL : [A-Z\u00C0-\u00D6\u00D8-\u00DE] ;
fragment SMALL   : [a-z\u00DF-\u00F6\u00F8-\u00FF] ;
fragment DIGIT   : [0-9] ;
Surrogate_id_SYMB_0 : '=' ;
Surrogate_id_SYMB_1 : '(' ;
Surrogate_id_SYMB_2 : ')' ;
Surrogate_id_SYMB_3 : '++' ;
Surrogate_id_SYMB_4 : '#' ;
Surrogate_id_SYMB_5 : '[' ;
Surrogate_id_SYMB_6 : ']' ;
Surrogate_id_SYMB_7 : ',' ;
Surrogate_id_SYMB_8 : 'Field' ;
Surrogate_id_SYMB_9 : 'Just' ;
Surrogate_id_SYMB_10 : 'Nothing' ;
Surrogate_id_SYMB_11 : 'array' ;
Surrogate_id_SYMB_12 : 'constant' ;
Surrogate_id_SYMB_13 : 'drop' ;
Surrogate_id_SYMB_14 : 'extern' ;


VBOOL : 'True'|'False';
VFLOAT : '-'?DIGIT+'.'DIGIT+('e''-'?DIGIT+)?;
VINT : '-'?DIGIT+;
OPOne :
     'not'|'abs'|'signum'|'complement'|'recip'|'exp'|'sqrt'|'log'|'sin'|'cos'|'tan'|'asin'|'acos'|'atan'|'sinh'|'cosh'|'tanh'|'asinh'|'acosh'|'atanh'|'cast'|'unsafeCast';
OPTwo : '+'|
        '-'|
        '*'|
        'div' |
        'mod'|
        '/'|
        '**'|
        'logBase'|
        '<'|
        '<='|
        '=='|
        '/='|
        '>='|
        '>'|
        '&&'|
        '||'|
        'xor'|'==>'|'.&.'|'.|.'|'.^.'|'.>>.'|'.<<.'|'.!!';
OPThree : 'mux';
// String token type
STRING : '"' -> more, mode(STRINGMODE);



// Identifier token type
fragment
IDENTIFIER_FIRST : LETTER | '_';
IDENT : IDENTIFIER_FIRST (IDENTIFIER_FIRST | DIGIT)*;
// Whitespace
WS : (' ' | '\r' | '\t' | '\n' | '\f')+ ->  skip;
// Escapable sequences
fragment
Escapable : ('"' | '\\' | 'n' | 't' | 'r' | 'f');
ErrorToken : . ;
mode STRESCAPE;
STRESCAPED : Escapable  -> more, popMode ;
mode STRINGMODE;
STRINGESC : '\\' -> more , pushMode(STRESCAPE);
STRINGEND : '"' ->  type(STRING), mode(DEFAULT_MODE);
//STRINGTEXT : ~[\"\\] -> more;
